---
name: Backlog Limits Checker
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  backlogger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: kalikiana/backlogger@main
        with:
          redmine_api_key: ${{ secrets.REDMINE_API_KEY }}
          args: --reminder-comment-on-issues
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages
          clean-exclude: pr-preview
