---
name: Backlog Limits Checker
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  backlogger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
        with:
          persist-credentials: false
      - uses: openSUSE/backlogger@3d037a7decf5a6baf4adb762d4bb33058c5f1ee1  # main
        with:
          redmine_api_key: ${{ secrets.REDMINE_API_KEY }}
          args: --reminder-comment-on-issues
      - uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f  # v4
        with:
          folder: gh-pages
          clean-exclude: pr-preview
